node download.js "בנימין נתניהו" &
node download.js "יולי אדלשטיין" &
node download.js 'ישראל כ"ץ' &
node download.js "מירי רגב" &
node download.js "יריב לוין" &
node download.js "יואב גלנט" &
node download.js "ניר ברקת" &
node download.js "גילה גמליאל" &
node download.js "אבי דיכטר" &
node download.js "גלית דיסטל-אטבריאן" &
node download.js "חיים כץ" &
node download.js "אלי כהן" &
node download.js "צחי הנגבי" &
node download.js "אופיר אקוניס" &
node download.js "יובל שטייניץ" &
node download.js "דודי אמסלם" &
node download.js "גדי יברקן" &
node download.js "אמיר אוחנה" &
node download.js "אופיר כץ" &
node download.js "אתי עטייה" &
node download.js "יואב קיש" &
node download.js "דוד ביטן" &
node download.js "קרן ברק" &
node download.js "שלמה קרעי" &
node download.js "מיקי זוהר" &
node download.js "אורלי לוי-אבקסיס" &
node download.js "קטי שטרית" &
node download.js "פטין מולא" &
node download.js "מאי גולן" &
node download.js "יאיר לפיד" &
node download.js "אורנה ברביבאי" &
node download.js "מאיר כהן" &
node download.js "קארין אלהרר" &
node download.js "מירב כהן" &
node download.js "יואל רזבוזוב" &
node download.js "אלעזר שטרן" &
node download.js "מיקי לוי" &
node download.js "מירב בן ארי" &
node download.js "רם בן ברק" &
node download.js "יואב סגלוביץ" &
node download.js "בועז טופורובסקי" &
node download.js "עידן רול" &
node download.js "יוראי להב-הרצנו" &
node download.js "ולדימיר בליאק" &
node download.js "רון כץ" &
node download.js "נירה שפק" &
node download.js "טניה מזרסקי" &
node download.js "יסמין פרידמן" &
node download.js "ענבר בזק" &
node download.js "משה טור-פז" &
node download.js "סימון דוידסון" &
node download.js "אריה דרעי" &
node download.js "יעקב מרגי" &
node download.js "יואב בן-צור" &
node download.js "מיכאל מלכיאלי" &
node download.js "חיים ביטון" &
node download.js "משה ארבל" &
node download.js "ינון אזולאי" &
node download.js "משה אבוטבול" &
node download.js "אוריאל בוסו" &
node download.js "יוסי טייב" &
node download.js "בני גנץ" &
node download.js "פנינה תמנו-שטה" &
node download.js "חילי טרופר" &
node download.js "מיכאל ביטון" &
node download.js "אורית פרקש-הכהן" &
node download.js "אלון שוסטר" &
node download.js "איתן גינזבורג" &
node download.js "יעל רון בן משה" &
node download.js "מופיד מרעי" &
node download.js "רות וסרמן-לנדה" &
node download.js "אלון טל" &
node download.js "מרב מיכאלי" &
node download.js "עמר בר לב" &
node download.js "אמילי מואטי" &
node download.js "גלעד קריב" &
node download.js "אפרת רייטן" &
node download.js "רם שפע" &
node download.js "אבתיסאם מראענה" &
node download.js "נעמה לזימי" &
node download.js "משה גפני" &
node download.js "יעקב ליצמן" &
node download.js "אורי מקלב" &
node download.js "מאיר פרוש" &
node download.js "יעקב אשר" &
node download.js "ישראל אייכלר" &
node download.js "יצחק פינדרוס" &
node download.js "יעקב טסלר" &
node download.js "אליהו ברוכי" &
node download.js "אביגדור ליברמן" &
node download.js "עודד פורר" &
node download.js "יבגני סובה" &
node download.js "אלי אבידר" &
node download.js "יוליה מלינובסקי" &
node download.js "חמד עמאר" &
node download.js "אלכס קושניר" &
node download.js "יוסי שיין" &
node download.js "לימור מגן-תלם" &
node download.js "אלינה ברדץ'-יאלוב" &
node download.js "שרון רופא-אופיר" &
node download.js "בצלאל סמוטריץ'" &
node download.js "מיכל וולדיגר" &
node download.js "איתמר בן גביר" &
node download.js "שמחה רוטמן" &
node download.js "אורית סטרוק" &
node download.js "אבי מעוז" &
node download.js "אופיר סופר" &
node download.js "נפתלי בנט" &
node download.js "איילת שקד" &
node download.js "מתן כהנא" &
node download.js "ניר אורבך" &
node download.js "אביר קארה" &
node download.js "עידית סילמן" &
node download.js "שירלי פינטו" &
node download.js "יום טוב כלפון" &
node download.js "איימן עודה" &
node download.js "אחמד טיבי" &
node download.js "סאמי אבו שחאדה" &
node download.js "עאידה תומא-סלימאן" &
node download.js "אוסאמה סעדי" &
node download.js "עופר כסיף" &
node download.js "גדעון סער" &
node download.js "יפעת שאשא-ביטון" &
node download.js "זאב אלקין" &
node download.js "יועז הנדל" &
node download.js "שרן השכל" &
node download.js "זאב בנימין בגין" &
node download.js "מאיר יצחק-הלוי" &
node download.js "צבי האוזר" &
node download.js "מיכל שיר" &
node download.js "ניצן הורוביץ" &
node download.js "תמר זנדברג" &
node download.js "יאיר גולן" &
node download.js "ג'ידא רינאווי זועבי" &
node download.js "עיסאווי פריג'" &
node download.js "מוסי רז" &
node download.js "מיכל רוזין" &
node download.js "גבי לסקי" &
node download.js "עלי סלאלחה" &
node download.js "מנסור עבאס" &
node download.js "מאזן גנאים" &
node download.js "וליד טאהא" &
node download.js "סעיד אלח'רומי" &
node download.js "אימאן ח'טיב-יאסין" &
node download.js "עמיחי שיקלי" &
